### ISSUE TITLE
Establish a discussion forum

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/FIPs#3]
Some "official" channel for discussions should be open(ed). Options for these include:
- Telegram (not most appropriate as topics are hard to track)
- Discord (seems to have a lively uptake, for some other projects, e.g. Swarm)
- Github discussions (has the benefit of being integrated with Github - the identity of users is "known" and issues/PRs/discussions/RFCs can be refrenced)

**Comment by nugaon** [comment]
I think for discussions/chatting we mainly should use Discord and when a long and well formatted opinion/request/idea comes, it should be in a form of RFC PR or a review comment on a PR.
So overall, I would prefer Discord as the first platform to exchange ideas.

**Comment by tfius** [comment]
Github discussions and discourse +1

**Comment by crtahlin** [comment]
Seems there were a lot of possible combinations listed.

I would say the general idea would be, that when some material appears on Github (either RFC document or after it the reference implementation) the discussions should be kept in Github - either in the Discussions, as an Issue or Pull request Issue, whatever may be the case.

Preliminary discussion should start on a channel where there are people to discuss them - which is at this point Discord, but can be another or additional channel at some later time.

**Comment by crtahlin** [comment]
Discord for FDS has been opened: https://discord.gg/KrVTmahcUA

**Comment by crtahlin** [comment]
In Discord, there is the #fdp-general channel , which can be used for discussion.
