### ISSUE TITLE
Establish a channel where call to FCPs can be published

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/FIPs#5]
FCPs is Final Comment Period; the full community gets asked to comment on the RFC, if any final objections.

This could be done via a main channel to communicate with community 
- Discord channel; if applicable
- Email list; if we establish one

It could be also done via several channels.

**Comment by nugaon** [comment]
I think we could broadcast on both channels listed, although I'm not sure we need more than that.

**Comment by crtahlin** [comment]
Yes, all the interested parties would be there. Would even change this to:
- Discord channel 
- Github Discussion tied to the RFC. 

But let's reevaluate when we get here.

**Comment by crtahlin** [comment]
Discord server for FDS is at: https://discord.gg/KrVTmahcUA
With channel for Fairdrive protocol.

**Comment by crtahlin** [comment]
Closing as channels are open.
